/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'AT32M412CBT7_Lvgl' 
 * Target:  'AT32M412CBT7_Lvgl' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Acceleration:Arm-2D:Core@1.2.4-dev */
#define ___ARM_2D_CFG_SKIP_HEADER___
/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.4.0 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1


#endif /* PRE_INCLUDE_GLOBAL_H */
