/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'AT32M412CBT7_Lvgl' 
 * Target:  'AT32M412CBT7_Lvgl' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "at32m412_416.h"

/* ARM::Acceleration:Arm-2D Demos:Monochrome@1.6.1 */
#define RTE_Acceleration_Arm_2D_Demos_Monochrome
/* ARM::Acceleration:Arm-2D Extras:Controls@2.6.9 */
#define RTE_Acceleration_Arm_2D_Extra_Controls
/* ARM::Acceleration:Arm-2D Extras:LCD ASCII Printf@2.13.1 */
#define RTE_Acceleration_Arm_2D_Extra_LCD_printf
/* ARM::Acceleration:Arm-2D Extras:Loaders@2.1.1 */
#define RTE_Acceleration_Arm_2D_Extra_Loaders
    #define RTE_Acceleration_Arm_2D_Extra_TJpgDec_Loader
/* ARM::Acceleration:Arm-2D Helper:Display Adapter@3.4.0 */
#define RTE_Acceleration_Arm_2D_Helper_Disp_Adapter0
    #define __RTE_ACCELERATION_ARM_2D_HELPER_DISP_ADAPTER0__  /* this macro is deprecated, please use the macro above in your code */

/* ARM::Acceleration:Arm-2D Helper:PFB@2.7.3 */
#define RTE_Acceleration_Arm_2D_Helper_PFB
/* ARM::Acceleration:Arm-2D Helper:Scene@1.3.3 */
#define RTE_Acceleration_Arm_2D_Scene0
    #define __RTE_ACCELERATION_ARM_2D_SCENE0__    /* this macro is deprecated, please use the macro above in your code */

/* ARM::Acceleration:Arm-2D:Alpha-Blending@1.2.4-dev */
#define RTE_Acceleration_Arm_2D_Alpha_Blending
/* ARM::Acceleration:Arm-2D:Core@1.2.4-dev */
#define RTE_Acceleration_Arm_2D
#define __RTE_ACCELERATION_ARM_2D__     /* this macro is deprecated, please use the macro above in your code */
/* ARM::Acceleration:Arm-2D:Filter@1.2.4-dev */
#define RTE_Acceleration_Arm_2D_Filter
/* ARM::Acceleration:Arm-2D:Transform@1.2.4-dev */
#define RTE_Acceleration_Arm_2D_Transform
/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.4.0 */
#define __PERF_COUNTER__ 1
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&Breakpoint@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
          #define RTE_Compiler_IO_STDOUT_BKPT     /* Compiler I/O: STDOUT Breakpoint */


#endif /* RTE_COMPONENTS_H */
